telegram:
  bot:
    token:
      ${TOKEN}
    #          Insert bot token. Example "1231312:jdhsjhfksjdfh"
    name:
      ${NAME}
    #      Insert bot name. Example "my_test_bot"
server:
  port: 8080

middle-server:
  url:
    http://localhost:9090
